i18n/tr.json
=> Translated to Turkish!

extension.json, i18n/en.json, resources/main.css, src/SpecialConfirmAccounts.php, src/SpecialRequestAccount.php
- Fully i18n
- Removed hard-written HTML and CSS
=> Fully i18n

i18n/en.json
=> Fix done messages

i18n/en.json, resources/main.css, src/ScratchConfirmAccountHooks.php, src/SpecialRequestAccount.php, src/database/DatabaseInteractions.php
RecentChanges bar was improved.
- It uses the previous CA-styled bar, ported from Ken's Report extension
- It shows when either of these exists, and shows the sum:
- "new"
- "awaiting-admin" and the user has been involved in the request at least once
=> Better RecentChanges bar

src/objects/AccountRequest.php
This affects ConfirmAccounts "last updated" section
=> Fix AccountRequest.lastUpdated not being set

i18n/en.json, i18n/tr.json
=> Tranlated to Turkish completely

i18n/ja.json
=> Update Japanese i18n

README.md, extension.json, i18n/en.json, i18n/ja.json, i18n/qqq.json, src/RequestPage.php, src/database/DatabaseInteractions.php
If $wgAutoWelcomeNewUsers is true (default) it automatically creates talk page to welcome the user.
=> Welcome users on talk page

i18n/ru.json
Because of #74, I translated new lines to Russian and fixed one.
=> Translated new lines to Russian (copy button)

src/PurgeAccountRequestPasswordsJob.php, src/RequestPage.php, src/ScratchConfirmAccountHooks.php, src/SpecialConfirmAccounts.php, src/SpecialRequestAccount.php, src/database/CheckUserIntegration.php, src/database/DatabaseInteractions.php, src/email.php
=> Added atomic database operations to avoid race conditions

resources/main.css, src/SpecialRequestAccount.php
=> re-edit for JS-disabled support

src/database/DatabaseInteractions.php
=> added null check to avoid null from propagating out in hasActiveRequest query

i18n/en.json, src/SpecialRequestAccount.php
=> check for IP account creation blocks when submitting requests

i18n/en.json, src/RequestPage.php, src/SpecialConfirmAccounts.php, src/SpecialRequestAccount.php, src/database/DatabaseInteractions.php
=> Prevent empty comments and cancel transactions on error rather than committing

src/SpecialRequestAccount.php
Another improvement to #92 but does not completely fix it.
=> moved all database queries after Scratch verification to mitigate race condition delay caused by HTTP request

src/database/DatabaseInteractions.php
=> Added more efficient implementation for RC hook

i18n/en.json, i18n/qqq.json, sql/requests_activeusername.sql, src/ScratchConfirmAccountHooks.php, src/SpecialRequestAccount.php, src/database/DatabaseInteractions.php
=> Use unique active_username key for account requests to prohibit duplicates

src/RequestPage.php, src/objects/AccountRequest.php
=> Don't allow commenting on expired requests

src/RequestPage.php, src/database/DatabaseInteractions.php
See commit messages for more info
=> Remove use of deprecated APIs

src/verification/ScratchVerification.php
=> use colon-split hex codes for verification

README.md, src/database/DatabaseInteractions.php
=> Avoid duplicate auto rejection comments

i18n/en.json, i18n/qqq.json, resources/main.css, src/RequestPage.php, src/SpecialConfirmAccounts.php, src/SpecialRequestAccount.php
=> Show an action conflict warning on account requests

src/RequestPage.php
=> use $pageContext instead of $this

extension.json, i18n/en.json, i18n/qqq.json, resources/main.js, src/SpecialRequestAccount.php
=> Use OOUI on Special:RequestAccount and include a password warning

extension.json, i18n/en.json, i18n/qqq.json, resources/main.js, sql/block_expiration_timestamp.sql, sql/blocks.sql, src/RequestPage.php, src/ScratchConfirmAccountHooks.php, src/SpecialConfirmAccounts.php, src/SpecialRequestAccount.php, src/common.php, src/database/DatabaseInteractions.php, src/jobs/ExpiredBlockCleanupJob.php, src/objects/AccountRequest.php
Resolves #138 
This basically works like the protection form. Existing blocks are all treated as infinite block since they default to null.
=> Add expiration dates to blocks

src/ScratchConfirmAccount.i18n.alias.php
=> fixed typo in french

extension.json, src/ScratchConfirmAccountHooks.php
=> remove use of PersonalUrls hook

extension.json, src/SpecialConfirmAccounts.php, src/SpecialRequestAccount.php, src/subpages/RequestPage.php, src/verification/ScratchVerification.php
=> remove JobQueueGroup::singleton

src/database/CheckUserIntegration.php
=> use IPUtils instead of IP for check user integration

src/common.php
Uses Absolute Human-Readable Times Similar To Time Preferences. Closes #185
=> Add Human-Readable Timestamp
